### ISSUE TITLE
Bug with Country look alike species tab

### ISSUE THREAD

**Issue by simaob** [Vizzuality/csn-tool#169]
On this page: http://localhost:3000/en/countries/ISL/lookAlikeSpecies?zoom=5&lat=65.02721817716994&lng=-19.015666824647692&view=map there is no data being rendered. I think it might be an issue with the query that is being performed, but maybe there's a Javascript bug. Can you check it out to see what might be the issue? Thanks!

If it's the query would you feel comfortable trying to optimize it?

**Comment by dancer2090** [comment]
@simaob I found the problem.
Error response from the server: 
You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details.

There are ways to fix it:
- increase a memory and timeout limit for SQL database. (not recommended, but can fix the problem quickly)
- remove some rows from the table (when I removed the row "No. of look-alike species populations in Col A" and all data that needs to calculate it from SQL request everything starts to work ) (quick way)
- modify a database for fetching the data quickly (not through few tables). I need access to DB or DB copy to do it. (not a quick way)

**Comment by dancer2090** [comment]
@simaob ! I have fixed the problem.
hi @simaob ! I have 2 additional questions about this task:
1) I am not sure that sql request fetch correct data for this fields. Can you , please, describe the columns in alike specials tab:
- No. of look-alike species populations
- No. of look-alike species populations in Col A
What data should be here?

2) In the current project we do the sql requests by using http request. And without credentials (just url and sql request). I think it is not safe. Are you sure that it is the correct way for getting data ftom server? Is database protected if i send SQL DROP table request?

**Comment by simaob** [comment]
Thanks for this Ivan, I'm checking the PR and will get the answers to your 1st question.

Regarding the question about DB access, we should be OK. We don't use any token so we just have read access from external applications. The requests could potentially be done via HTTPS instead of HTTP, but other than that, I don't think we need to worry.

From their documentation:

> CARTO uses the database access mechanism for security. Every writable connection is verified by an API Key. If you have the correct API Key, you can write-access to the database. If you do not have the correct API Key, your client is “logged in” as a low privilege user, and you have read-only access to the database (if the database allows you to read).

**Comment by simaob** [comment]
I just tested it and the page now loads, but if I try to go into the detail, by clicking on the arrow, I get a never ending load. So maybe that one is suffering from the same issue.

Regarding your question: I didn't manage to check my notes but will do that tomorrow morning. Thanks!

**Comment by dancer2090** [comment]
Ok, i will check it.

**Comment by dancer2090** [comment]
@simaob I have updated the request for lookalikespecies.
The description of changes here:
https://docs.google.com/document/d/1kcuHemqr7Q2b0GzomRsjrChQC6dxRo-QmJdgxxo6gZ0/edit?usp=sharing
Let me know if you have any questions.
The second request i need to check - looksalikespecies population
