### ISSUE TITLE
Climate Suitability Layers

### ISSUE THREAD

**Issue by simaob** [Vizzuality/csn-tool#173]
I started working on a feature to enable Climate Suitability Layers to be displayed on the Species Show page. This is still work in progress on the rendering of the layers, but we also need to do some work on the legend. There are quite a few layers to display and they should be organised in a matrix. I'm working on this branch `feature/adding-climate-change-layers`

If you visit a Species page, e.g.: http://localhost:3000/en/species/22679763?zoom=4&lat=4.849811985024993&lng=10.687294006347658&view=map you can see some layers on the legend:

<img width="1279" alt="Screenshot 2020-02-12 at 09 37 37" src="https://user-images.githubusercontent.com/10764/74322095-53c5a780-4d7b-11ea-8cd7-3cef506c682c.png">

The Climate Change Present Suitability and Future Suitability, then there are different variations from these based on the season: breeding, passage, winter, sedentary. And there is a "Gains" variation, which should show how things changed. For some variations the layer renders, though not matching the legend yet:

<img width="1280" alt="Screenshot 2020-02-12 at 09 39 15" src="https://user-images.githubusercontent.com/10764/74322270-96877f80-4d7b-11ea-9d71-b7f6e159f33e.png">

The first task on this is to change the way the legend for this is organised, instead of multiple rows, there should be a matrix/table like:

|                    |   Present Suitability |  Future Suitability | Gains                   |
|------------|---------------------|-------------------|-----------------|
| Breeding    | []   (radio button)     | []  (radio button)   | [] (radio button) |
| Passage     | []   (radio button)     | []  (radio button)   | [] (radio button) |
| Winter        | []   (radio button)     | []  (radio button)   | [] (radio button) |
| Sedentary  | []   (radio button)     | []  (radio button)   | [] (radio button) |

**Comment by dancer2090** [comment]
hi @simaob ! I have provided changes in this branch: https://github.com/Vizzuality/csn-tool/tree/feature/adding-climate-change-layers-legends

sublayers of  'climate_future', 'climate_present', 'climate_gains' layers add to table as rows.
1. At that moment 'climate_gains' is not in data list. We should add this.
2.  The table headers set as text. We need to add translations for them. 

Wrong logic:
Only Present Suitability layer comes with Gains sublayer (it look like a bug).

**Comment by simaob** [comment]
Notes from meeting with Lammert:

- Remo row for Gains, and include Gains/Losses in the same column, with different colour for each of them.

**Comment by simaob** [comment]
As discussed, here the details of this feature:


Climate Change Layers:

- Each species can have 4 layers:

  - wetlands.{speciesId}_{season}

Seasons are:
  - b -> breeding;
  - w -> wintering;
  - p -> passage;
  - S -> Sedentary;

Inside of each of the layers there is coded information:
  - present information;
  - future information;

Each layer has multiple pixels, but each pixel has a RGBa value:
  - Red band;
  - Green band;
  - Blue band;
  - Alpha;

Data is encoded in each of those values:
  - Red band-> present suitability;
  - Green band -> future suitability;
  - B and A are rubbish;

We decode the data in this file: app//helpers/filterPixel.js;

For each species and season, besides the future and present suitability we want to show a third thing which is "Gains and Losses", that should the difference between "presetn" and "future" suitability;

The options on the matrix should be:

- For season "b" (breeding), if user selects "Present suitaiblity", we show the layer "{speciesId}_b", but only the values inside the "r" band of the layer;
- For season "b" (breeding), if user selects "Future suitability", we show the layer "{speciesId}_b", but only the values inside the "b" band of the layer;
- For season "b" (breeding), if suer selects "Gains and Losses", we show the layer "{speciesId}_b", but only the following colour per pixel based in logic:
  - pixel should be green if "r" band is undefined and "b" band is defined; <--- Suitability was gained!
  - pixel should be red if "b" band is undefined and "r" band is defined; <--- Suitability was lost;


Final Matrix is:
                  Present suitability |  Future Suitability | Gains and Losses
b (breeding)  
w (wintering)
p (passage)
S (sendentary)


Files for reference:

- Layer definition is currently on: app/components/maps/ClimateMap.js
- Pixel filtering currently on: app/helpers/filterPixel.js
- Legend setup: app/components/maps/Legend.js

**Comment by dancer2090** [comment]
I have done all changes:
- Gains/Losses layers in lagends. Bugfix.
- RGB filter fix
- Climate layer legend change fix.
- Climate layer legend color rages
. Branch - https://github.com/Vizzuality/csn-tool/tree/feature/adding-climate-change-layers-legends

**Comment by simaob** [comment]
Great job, looking really great. I've showed it to Lammert and there are just a few more adjustments needed:

- It turns out that it would be useful to allow the Gains/Losses layer to be turned on together with the other two. So we should change the behaviour/setup of the radio buttons, so that "Gains/Losses" is independent of the other two. This will allow users to see the combination of "Present + Gains/Losses" and "Future + Gains/Losses"
- let's change the left colour of Gains/Losses to be Blue, instead of green. So that it can be more easily compared with the Present and Future;
- We need to make these rows dynamic, based on the information that exists on this table: https://csntool-v2.carto.com/dataset/table_1_species . So we should disable the radio buttons for seasons that are not relevant for a given species. On that table "ssis" is the species ID, an example query to get the relevant info is: `SELECT DISTINCT season FROM table_1_species WHERE ssis = 22680415`

**Comment by dancer2090** [comment]
Hi @simaob ! 
https://github.com/Vizzuality/csn-tool/tree/feature/adding-climate-change-layers-legends
I have done all changes:
 - Gains/Losses layer can be active with other 2 layers in season. I added option to display the data only for one season. As for me, it is good (it helps to understand what season on the map). If we need to change it, let me know.
 - Gains/Losses green color has beed changed to blue.
 - added seasons filter. Show only layers with seasons in the database.
