### ISSUE TITLE
Investigate why Look-alike Species for Russia are not showing up

### ISSUE THREAD

**Issue by simaob** [Vizzuality/csn-tool#175]
Url: https://criticalsites.wetlands.org/en/countries/RUS/lookAlikeSpecies

**Comment by simaob** [comment]
On this page we should be seeing Look Alike Species information for Russia. It is possible that this data is missing from CARTO or that is not correctly linked, as the original data source had Russia information spread across multiple tables.

**Comment by dancer2090** [comment]
Checked on carto.com ... species_country table doesn't have a rows with iso = 'RUS'. 
For species fetching in other requests, we use the countries table.

**Comment by dancer2090** [comment]
Update iso value for Russian county id in species_countries.

**Comment by dancer2090** [comment]
Fixed: Have run SQL request in the Carto system.
Update species_country SET iso='RUS' WHERE id=1000;

1000 - the country id from countries table (Russian Federation)
RUS - the iso3 from countries table.

Tested on website. Data is available for RUS - lookAlikeSpecies, lookAlikeSpecies populations.
