### ISSUE TITLE
Overlay AEWA area polygon

### ISSUE THREAD

**Issue by simaob** [Vizzuality/csn-tool#179]

**Comment by simaob** [comment]
Hey @lhilarides , do you know where we can find this data? Thanks!

**Comment by lhilarides** [comment]
[AEWA.zip](https://github.com/Vizzuality/csn-tool/files/4388661/AEWA.zip)

**Comment by simaob** [comment]
@dancer2090 I uploaded this new layer to CARTO, you can find it here: https://csntool-v2.carto.com/dataset/aewa_extent_geo

The goal is to include a new item on the legend that would allow users to see this layer overlayed on the map. It can be called "AEWA Extent" to start with, and should be quite transparent with a light yellow colour. This shows the area of action of the AEWA agreement.

**Comment by dancer2090** [comment]
@simaob  aewa area added to countries page:
https://github.com/Vizzuality/csn-tool/pull/186
