### ISSUE TITLE
UI improvement - details button

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/csn-tool#182]
Small request: could we make the "View details" button a bit more prominent? I've had two people asking me about it this week and I kind of agree with them. I think if we flip the colors (so yellow when inactive and light-grey when hover) and increase the size a bit it will already help a lot.

![image](https://user-images.githubusercontent.com/3919721/77341302-d05e8500-6d2e-11ea-92e7-ae614163c77e.png)

**Comment by dancer2090** [comment]
A small style fix here: 
https://github.com/Vizzuality/csn-tool/pull/184
