### ISSUE TITLE
New (?) issue with populations on Countries page

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/csn-tool#185]
e.g. this page has only a fraction of the populations we should see: 
https://criticalsites.wetlands.org/en/countries/SEN/populations?zoom=8&lat=14.51075502534272&lng=-14.437175832904972&view=map

[download (63).zip](https://github.com/Vizzuality/csn-tool/files/4389950/download.63.zip)

Real list is attached:

**Comment by dancer2090** [comment]
The result comes with error property:
That is a reason why we can not fetch all populations.
"rows": [],
"fields": {},
"total_rows": "",
"error": [
        "You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details."
]
This is the same problem we have here:

**Comment by simaob** [comment]
This should now be fixed, since the account was upgraded, I can see lots of populations on that page. =)
