### ISSUE TITLE
Species map page legend

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/csn-tool#190]
On the species map page, the legend no longer works correctly. For example, I cannot switch on or off the inundation layer on that page. Only the species distribution layer legend works

![image](https://user-images.githubusercontent.com/3919721/78990718-7552cd80-7b37-11ea-84b9-e9c8c9c7a54e.png)

**Comment by lhilarides** [comment]
Maybe this example is a bit more clear:
Direct link: http://criticalsites.wetlands.org/en/species/22679746?zoom=4&lat=25.403584973186703&lng=24.389648437500004&view=map

![image](https://user-images.githubusercontent.com/3919721/78990866-d2e71a00-7b37-11ea-9830-af4dbf93ea8c.png)

**Comment by simaob** [comment]
This is now fixed and deployed to production.
